export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"


eval "$(starship init zsh)"

#export LS_COLORS="di=36:fi=37:ln=32:pi=33:so=35:bd=34;46:cd=34;43:or=31;41:mi=05;37;41:ex=01;32:*~=.;30:"


if [[ -f $(brew --prefix)/etc/profile.d/coreutils.sh ]]; then
  source $(brew --prefix)/etc/profile.d/coreutils.sh
fi

alias ls='eza'
eval $(gdircolors -b ~/.dir_colors)
